steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-cloud-run-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/my-cloud-run-app']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'my-cloud-run-app', '--image', 'gcr.io/$PROJECT_ID/my-cloud-run-app', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']
images:
- 'gcr.io/$PROJECT_ID/my-cloud-run-app'
options:
  logging: CLOUD_LOGGING_ONLY
